import os

TOKEN = os.getenv("DISCORD_TOKEN")
MONGODB_URI = os.getenv("MONGODB_URI")

# Number of drivers to predict
NUM_DRIVERS_PREDICT = 10
# Number of players to be displayed on leaderboard
LEADERBOARD_LENGTH = 10

#### POINTS SYSTEM ####

DISTANCE_TO_RECIEVE_POINTS = 2
DISTANCE_POINTS = 1

POINTS_CORRECT_P1 = 6
POINTS_CORRECT_P2 = 3
POINTS_CORRECT_P3 = 3
POINTS_CORRECT_P4 = 3
POINTS_CORRECT_P5 = 3
POINTS_CORRECT_P6 = 2
POINTS_CORRECT_P7 = 2
POINTS_CORRECT_P8 = 2
POINTS_CORRECT_P9 = 2
POINTS_CORRECT_P10 = 2

POINTS_CORRECT_TOP_3 = 10
POINTS_CORRECT_3_DRIVERS = 5

POINTS_CORRECT_TOP_5 = 14
POINTS_CORRECT_5_DRIVERS = 10

POINTS_CORRECT_TOP_10 = 30
POINTS_CORRECT_10_DRIVERS = 14

