from config.settings import POINTS_CORRECT_P1, POINTS_CORRECT_P2, POINTS_CORRECT_P3, POINTS_CORRECT_P4, POINTS_CORRECT_P5, POINTS_CORRECT_P6, POINTS_CORRECT_P7, POINTS_CORRECT_P8, POINTS_CORRECT_P9, POINTS_CORRECT_P10
points_per_position = {
  1: POINTS_CORRECT_P1, 
  2: POINTS_CORRECT_P2,
  3: POINTS_CORRECT_P3,
  4: POINTS_CORRECT_P4,
  5: POINTS_CORRECT_P5,
  6: POINTS_CORRECT_P6,
  7: POINTS_CORRECT_P7,
  8: POINTS_CORRECT_P8,
  9: POINTS_CORRECT_P9,
  10: POINTS_CORRECT_P10,
}